# -*- coding: utf-8 -*-
"""Calculadora de Horas_2.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5-O-08ir0r10JXNsnXSMf1U1PTSKEnX
"""

from datetime import datetime, timedelta

Horario_entrada = input("Entrada (HH:mm): ")
Entrada = datetime.strptime(Horario_entrada, "%H:%M")

Horario_intervalo = input("Intervalo (HH:mm): ")
Intervalo = datetime.strptime(Horario_intervalo, "%H:%M")

horario_volta = input("Volta (HH:mm): ")
Volta = datetime.strptime(horario_volta, "%H:%M")

Horario_saida = input("Saida (HH:mm): ")
Saida = datetime.strptime(Horario_saida, "%H:%M")

Horas_trabalhadas = (Intervalo - Entrada) + (Saida - Volta)

Horas_extras = Horas_trabalhadas - timedelta(hours=8)

if Horas_extras < timedelta(0):
    Horas_faltantes = abs(Horas_extras)
    print(f"Horas faltantes: {Horas_faltantes}")
else:
    print(f"Horas extras: {Horas_extras}")

